<a href="https://colab.research.google.com/github/Seungkyu-Han/colab_ml/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install scikit-learn

In [2]:
import numpy as np

In [3]:
array1 = np.array([1, 2, 3, 4])

In [4]:
print(array1)

[1 2 3 4]


In [5]:
print(array1.shape)

(4,)


In [6]:
array2 = np.array([[1, 2, 3], [4, 5, 6]])

In [7]:
array2.shape

(2, 3)

In [8]:
array1.dtype

dtype('int64')

### Numpy ndarray 개요

In [9]:
import numpy as np

In [10]:
list1 = [1, 2, 3]
print(f"list1 type: {type(list1)}")

array1 = np.array(list1)

print("array1 type: ", type(array1))
print("array1 shape: ", array1.shape)

array2 = np.array(
    [[1, 2, 3],
    [4, 5, 6],
    ]
)

print("array2 type: ", type(array2))
print("array2 shape: ", array2.shape)

array3 = np.array([[1, 2, 3]])
print("array3 type: ", type(array3))
print("array3 shape: ", array3.shape)


list1 type: <class 'list'>
array1 type:  <class 'numpy.ndarray'>
array1 shape:  (3,)
array2 type:  <class 'numpy.ndarray'>
array2 shape:  (2, 3)
array3 type:  <class 'numpy.ndarray'>
array3 shape:  (1, 3)


### ndarray의 데이터 타입

In [11]:
list1 = [1, 2, 3]
print(type(list1))

array1 = np.array(list1)
print(type(array1))

print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [12]:
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(type(array2))

print(array2, array2.dtype)

<class 'numpy.ndarray'>
['1' '2' 'test'] <U21


In [13]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_int.astype('int')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.0, 2.1, 3.2])
array_int2 = array_int.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int64
[1 2 3] int32


### ndarray를 편리하게 생성하기 - arange, zeros, ones

In [14]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [15]:
zero_array = np.zeros((3, 2), dtype=np.int32)
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3, 2), dtype=np.int32)
print(one_array)
print(one_array.dtype, one_array.shape)

one_3d_array = np.ones((3, 2, 2), dtype=np.int32)
print(one_3d_array)
print(one_3d_array.dtype, one_3d_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1 1]
 [1 1]
 [1 1]]
int32 (3, 2)
[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]
int32 (3, 2, 2)


### ndarray의 차원과 크기를 변경하는 reshape

In [16]:
array1 = np.arange(10)
print('array1: \n', array1)

array2 = array1.reshape(2, 5)
print('array2: \n', array2)

array3 = array1.reshape(5, 2)
print('array3: \n', array3)

array1: 
 [0 1 2 3 4 5 6 7 8 9]
array2: 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3: 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [17]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1, 5)
print('array2 shape: ', array2.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape:  (2, 5)


### 넘파이 ndarray의 데이터 세트 선택하기 - indexing

In [18]:
array1 = np.arange(start=1, stop=10)
print('array1: ', array1)

value = array1[2]
print('value: ', value)
print(type(value))

array1:  [1 2 3 4 5 6 7 8 9]
value:  3
<class 'numpy.int64'>


In [19]:
print(f"last data: {array1[-1]}")

last data: 9


In [20]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print(array2d)

print('(0, 0): ', array2d[0, 0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(0, 0):  1


In [21]:
array1 = np.arange(start=1, stop=10)
array4 = array1[0:3]

print(array4)

[1 2 3]


In [22]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)

print("array2d[0:2, 0:2] \n", array2d[0:2, 0:2])

array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]


In [23]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)

array3 = array2d[[0, 1], 2]
print('array2d[[0, 1], 2] => ', array3.tolist())

array2d[[0, 1], 2] =>  [3, 6]


In [25]:
array1d = np.arange(start=1, stop=10)
print(array1d)

array3 = array1d[array1d > 5]
print('array1d > 5: ', array3)



[1 2 3 4 5 6 7 8 9]
array1d > 5:  [6 7 8 9]


In [27]:
print(array1d[True])

[[1 2 3 4 5 6 7 8 9]]


### 행렬의 정렬 sort(), argsort()

In [29]:
org_array = np.array([3, 1, 9, 5])
print('원본 배열 ', org_array)

sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 배열: ', sort_array1)
print('np_sort() 호출 후 원본 배열', org_array)

sort_array2 = org_array.sort()
print('np.sort() 호출 후 반환된 정렬 배열: ', sort_array2)
print('np_sort() 호출 후 원본 배열', org_array)


원본 배열  [3 1 9 5]
np.sort() 호출 후 반환된 정렬 배열:  [1 3 5 9]
np_sort() 호출 후 원본 배열 [3 1 9 5]
np.sort() 호출 후 반환된 정렬 배열:  None
np_sort() 호출 후 원본 배열 [1 3 5 9]


In [31]:
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬: ', sort_array1_desc)

내림차순으로 정렬:  [9 5 3 1]


In [32]:
array2d = np.array(([9, 12], [7, 1]))

sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬: \n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('컬럼 방향으로 정렬: \n', sort_array2d_axis1)

로우 방향으로 정렬: 
 [[ 7  1]
 [ 9 12]]
컬럼 방향으로 정렬: 
 [[ 9 12]
 [ 1  7]]


In [33]:
org_array = np.array([3, 1, 9, 5])
sort_indices = np.argsort(org_array)

print(type(sort_indices))
print('행렬 정렬 시 원본 배열의 인덱스: ', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 배열의 인덱스:  [1 0 3 2]
