<a href="https://colab.research.google.com/github/Seungkyu-Han/colab_ml/blob/main/numpy_indexing_review.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### numpy ndarray의 데이터 세트 선택하기 - indexing

In [1]:
import numpy as np

In [2]:
array1 = np.arange(1, 10)
print('array1: ', array1)
value = array1[2]
print(f'value {value}')
print(type(value))

array1:  [1 2 3 4 5 6 7 8 9]
value 3
<class 'numpy.int64'>


In [3]:
array2d = array1.reshape(3, 3)
print(array2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
print(array2d[0, 0])
print(array2d[0, 1])
print(array2d[1, 0])

1
2
4


### 슬라이싱 인덱싱

In [5]:
array1 = np.arange(1, 10)
print('array1: ', array1)
array3 = array1[0: 3]
print('array3: ', array3)
print(type(array3))

array1:  [1 2 3 4 5 6 7 8 9]
array3:  [1 2 3]
<class 'numpy.ndarray'>


In [6]:
array1d = np.arange(1, 10)
array2d = array1d.reshape(3, 3)

print('array2d: ', array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])

array2d:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]


### 팬시 인덱싱

In [7]:
array1d = np.arange(1, 10)
array2d = array1d.reshape(3, 3)
print(array2d)

array3 = array2d[[0, 1], 2]
print('array2d[[0, 1], 2] => ', array3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[[0, 1], 2] =>  [3 6]


### 불린 인덱싱

In [8]:
array1d = np.arange(1, 10)
print(array1d)

array3 = array1d[array1d > 5]
print('array1d 중에서 5보다 큰 값', array3)

[1 2 3 4 5 6 7 8 9]
array1d 중에서 5보다 큰 값 [6 7 8 9]


### 정렬

In [9]:
org_array = np.array([3, 1, 9, 5])
sort_array1 = np.sort(org_array)
print(sort_array1)
print(org_array)

[1 3 5 9]
[3 1 9 5]


In [10]:
sort_array2 = org_array.sort()
print(sort_array2)
print(org_array)

None
[1 3 5 9]


In [11]:
sort_array1_desc = np.sort(org_array)[::-1]
sort_array1_desc

array([9, 5, 3, 1])

In [12]:
array2d = np.array([[8, 12], [7, 1]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print(sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print(sort_array2d_axis1)

[[ 7  1]
 [ 8 12]]
[[ 8 12]
 [ 1  7]]


In [13]:
org_array = np.array([3, 1, 9, 5])
sort_indices = np.argsort(org_array)

print(sort_indices)

[1 0 3 2]


### 행렬 내적

In [14]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8], [9, 10], [11, 12]])

dot_product = np.dot(A, B)

print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


### 전치 행렬

In [15]:
A = np.array([[1, 2], [3, 4]])

transpose_mat = np.transpose(A)
print('A의 전치 행렬', transpose_mat)

A의 전치 행렬 [[1 3]
 [2 4]]
